### ISSUE TITLE
specify number of threads?

### ISSUE THREAD

**Issue by ptitle** [vlasmirnov/GCM#29]
Hi,
Currently, when I run MAGUS, it uses all available cores, and starts maxing out the memory. Is it possible to specify the max number of threads to use? I see in magus_configuration.py `numCores = 1`, but clearly it is not limiting itself to 1 core. Maybe this is specified elsewhere?

Thanks!
-Pascal

**Comment by ptitle** [comment]
Ah, now I see -np NUMPROCS in the help. Probably that?

**Comment by RuneBlaze** [comment]
Hey. `-np` is supposed to control the number of threads used by MAGUS, so I would say definitely try that. I vaguely remember that MAGUS's parallelization strategy of MAFFT might launch several MAFFT instances, each using multiple threads, so in effect MAGUS might still be using more threads than `-np` (don't quote me on that).

If it is running out of memory and `-np` does not solve it, we might be able to diagnose more if we get a breakdown of the memory usage such as from `htop`, so that we learn which sub-component is causing the OOM. Edit: just want to add that it is entirely possible one of the subprograms (e.g., tree-inference, sub-alignment aligning) caused the OOM, so to know the root-cause a breakdown of the memory such as from `htop` will help.

(Obviously Vlad, the author of MAGUS, will know better. Just helping out here.)

**Comment by ptitle** [comment]
Thanks! Yes, when I specified `-np` it did limit the number of threads used by magus, and I could see that mafft was now using that reduced number of threads, but at various points, all threads were still getting used. I think you are right that mafft gets called in parallel, and is using that same number of threads each time. 

This still helped though, and my machine no longer maxed out on memory.

**Comment by RuneBlaze** [comment]
Well glad it helped! And thanks for reaching out. 

For future readers of this issue, `-np` defaults to the number physical cores in the machine, and it also determines the number of threads used in the sub-programs (e.g., MAFFT). Reducing `-np` can help with OOM issues (at the potential cost of speed).
